name: hcp
batch_size: 16
test_batch_size: 16
val_batch_size: 16
train_set: 0.7
val_set: 0.1
node_feature: /home/yongho/BrainNetReproduction/BrainNetworkTransformer/data/HCP_ROI_fisher.npy
# time_seires: /local/scratch/xkan/ABCD/ABCD/abcd_rest-timeseires-HCP2016.npy
# node_id: /local/scratch/xkan/ABCD/ABCD/ids_HCP2016.txt
# seires_id: /local/scratch/xkan/ABCD/ABCD/ids_HCP2016_timeseires.txt
label: /home/yongho/BrainNetReproduction/BrainNetworkTransformer/data/HCP_1200_precise_age.csv
label_int: /home/yongho/BrainNetReproduction/BrainNetworkTransformer/data/HCP_1200_gender.csv
drop_last: True
stratified: False
task: sex