defaults:
  - dataset: UKB
  - model: bnt # brainnetcnn, fbnetgen, bnt, transformer
  - optimizer: adam
  - training: basic_training
  - datasz: 100p
  - preprocess: mixup

repeat_time: 1
log_path: result
save_learnable_graph: False

# wandb
wandb_entity: brain_net
project: brain_net

task: age